Biblioteca/Controllers/LibroController.cs
using Biblioteca.Models.Entity;
using Biblioteca.Models.ViewModels.Libro;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.Controllers
{
    public class LibroController : Controller
    {

        // GET: Libro
        // miaplicacion.com/Libro/Index
        // miaplicacion.com/Libro/

        //public ActionResult Index()
        //{
        //    return View();
        //}
        // miaplicacion.com/Libro/Aleatorio
        // miaplicacion.com/Libro/
        /// <summary>
        /// Obtenemos un libro aleatoriamente 
        /// </summary>
        /// <returns></returns>
        public ActionResult Aleatorio()
        {
            BibliotecaEntities db = new BibliotecaEntities();

            Libro libro = db.Libro.FirstOrDefault();

              List<TablaSinSentido> sinSentido = db.TablaSinSentido.ToList();

            Aleatorio ViewModel = new Aleatorio();


            ViewModel.libro = libro;
            ViewModel.listaSinSentido = sinSentido;

            // db.Dispose();

            return View(ViewModel);
        }

       
        public ActionResult Edit(int valor)
        {

            return Content("valor : " + valor);
        }

        public ActionResult Index(int? pageIndex,string sorty)
        {

            if (!pageIndex.HasValue)
            {
                pageIndex = 1;
            }
            if (String.IsNullOrWhiteSpace(sorty))
            {
                sorty = "Titulo";

               
            }
            return Content(String.Format("pageIndex={0}&sorty={1}", pageIndex, sorty));

        }
        //esto es un metodo estatico, para que pueda funcionar se añade esto: [Route("Libro/metodo/{idBibioteca}/{titulo}")] y en routeconfigesto :routes.MapMvcAttributeRoutes();

        [Route("Libro/metodo/{idBibioteca:range(1,9999)}/{titulo:maxlength(5):minlength(3)}")]
        public ActionResult metodo(int idBibioteca, string titulo)
        {
          
            return Content(String.Format("idBibioteca={0}&titulo={1}", idBibioteca, titulo));

        }


    }
}

Biblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    

</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Biblioteca", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Mi pagina", "Aleatorio", "Libro")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@

    <nav class="navbar navbar-inverse sidebar" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href='@Url.Action("Index", "Home")'>Inicio<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a>
                
               
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @*<li class=""><a href="#">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                    <li><a href="#">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
                    <li><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>*@
                    @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>*@
                    @*<li><a href="#">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                    <li><a href="#">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
                    <li><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>*@
                    <li class="dropdown">

                        @*<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>*@
                        @*<ul class="dropdown-menu forAnimate" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>*@
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Libro <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></span></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li class="dropdown">@Html.ActionLink("Aleatorio prueba", "Aleatorio", "Libro")</li>
                        </ul>
                               <li class="dropdown">@Html.ActionLink("Categoria", "Index", "Categoria")</li>

                            @*</li>*@

                            <li> </li>
                        </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </nav>
    <div class="main">
        <!-- Content Here -->
        <div class="container body-content">
            @Scripts.Render("~/bundles/jquery")
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
            </footer>
        </div>
    </div>
    @*<div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>*@

   
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/Site")
    @RenderSection("scripts", required: false)
</body>
</html>